# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!
pod 'ReactiveCocoa'


target 'TestRAC2' do

end

target 'TestRAC2Tests' do

end

target 'TestRAC2UITests' do

end

